trigger:
- master

jobs:

- job: 'Test'
  pool:
    vmImage: 'Ubuntu-16.04'
  strategy:
    matrix:
      Python27:
        python.version: '2.7'
      Python35:
        python.version: '3.5'
      Python36:
        python.version: '3.6'
      Python37:
        python.version: '3.7'

  steps:
  - task: UsePythonVersion@0
    inputs:
      versionSpec: '$(python.version)'
      architecture: 'x64'

  - script: ci/travis_before_install.sh
    displayName: 'Install dependencies'

  - script: ci/travis_install.sh
    displayName: 'Install solvers'

  - script: ci/travis_script.sh
    displayName: 'nosetests'
